UiPath/Infrastructure

- Azure/Orchestrator/PaaS/Deploy/README.md
- Azure/Orchestrator/PaaS/Deploy/azuredeploy.json
Removed the location parameter and created variable to be taken directly from the RG 
Removed the passphrase parameter and created a variable with the RG ID so it could be unique. 
The user does not need to understand the internal works of the orchestrator. 
Testing, do no approve until done :)
> Less parameters alternative

- Azure/Orchestrator/PaaS/Upgrade/azuredeploy.json
@hteo1337 - Also tested and the upgrade works (from 18.6 to 19.4.4 - IIRC)
> Changed to match the deploy

- Azure/Orchestrator/PaaS/Upgrade/azuredeploy.json
Reverts UiPath/Infrastructure#3
The upgrade script don't work on azure marketplace or if RG is changed
> Revert "Changed to match the deploy"

- GCP/Terraform/Orchestrator/Single-Node/instances.tf
- GCP/Terraform/Orchestrator/Single-Node/ip-address.tf
- GCP/Terraform/Orchestrator/Single-Node/main.tf
- GCP/Terraform/Orchestrator/Single-Node/metadata.tf
- GCP/Terraform/Orchestrator/Single-Node/output.tf
- GCP/Terraform/Orchestrator/Single-Node/variables.tf
- Setup/Install-UiPathOrchestrator.ps1
Created single node orchestrator terraform scripts for GCP.
Updated Install-UipathOrchestrator.ps1 to enable TLS12 for invokeweb request.
> Terraform GCP Single-Node and Install-UipathOrchestrator.ps1 update

- AWS/Terraform/Orchestrator/single-node/main.tf
- AWS/Terraform/Orchestrator/single-node/variables.tf
> corrections

- Azure/Orchestrator/PaaS/Upgrade/README.md
Orchestrator upgrade to a minor version only
> Orchestrator upgrade to a minor version only

- AWS/Terraform/Robots/variables.tf
I updated us-east-1 with the correct AZ names and removed credentials.
> Fixed us-east-1/2's AZs & removed creds

- GCP/Terraform/Orchestrator/Multi-Node/.gitignore
- GCP/Terraform/Orchestrator/Multi-Node/README.md
- GCP/Terraform/Orchestrator/Multi-Node/fw.tf
- GCP/Terraform/Orchestrator/Multi-Node/ip-address.tf
- GCP/Terraform/Orchestrator/Multi-Node/lb.tf
- GCP/Terraform/Orchestrator/Multi-Node/metadata.tf
- GCP/Terraform/Orchestrator/Multi-Node/mig.tf
- GCP/Terraform/Orchestrator/Multi-Node/network.tf
- GCP/Terraform/Orchestrator/Multi-Node/outputs.tf
- GCP/Terraform/Orchestrator/Multi-Node/providers.tf
- GCP/Terraform/Orchestrator/Multi-Node/redis.tf
- GCP/Terraform/Orchestrator/Multi-Node/sql.tf
- GCP/Terraform/Orchestrator/Multi-Node/variables.tf
> Draft of multi-node orchestrator deploy

- ML/du_prereq_installer.sh
- added logging
- added cuda support
- fixes some issues (missing wget and pciutils)
- additional checks if the packages exists
- added check if plugin exist
> AIF updated script

- AWS/Terraform/Robots/data-template.tf
- GCP/Terraform/UiRobot/metadata.tf
- Setup/Install-UiRobot.ps1
Description of changes:
- added new parameter MachineName used as Machine name for Robot deployment in Orchestrator
> new parameter MachineName & TF fixes

- ML/du_prereq_installer.sh
Added optional arg for changing docker root mount path.
> OPT ARG --change-mount

- AWS/Terraform/Orchestrator/multi-node/variables.tf
> Updating availability zones

- Azure/Orchestrator/PaaS/WebHooks/README.md
- Azure/Orchestrator/PaaS/WebHooks/azuredeploy.json
Changes : 
+ added readme
- removed service plan as we don't need for existing webapp
> # UiPathOrchestrator WebHooks - add Readme

- ML/README.md
- ML/du_prereq_installer.sh
Rename flags serving to cpu and training to gpu in the du_prereq_installer.sh script
> Rename flags in the du_prereq_installer.sh script

- Azure/Archive/Orchestrator/PaaS/Deploy/README.md
- Azure/Archive/Orchestrator/PaaS/Deploy/azuredeploy.json
- added 19.10.21 for old ARM template for Orchestrator
- changed url for Deploy button to reflect the new path
> 19.10.21 - Orchestrator 

- Azure/AIFabric/README.md
- Azure/AIFabric/mainTemplate.json
- Azure/AIFabric/mainTemplate.parameters.json
Solving usability and readme issues related to AI Fabric:
- restrict Kubernetes versions
- remove ACR option from parameters
- add Orchestrator hostname tooltip with example
- add link to ARM user assigned identity objects
- remove UTC value
> fix issues with AI Fabric

- ML/ml_prereq_podman_rhel8.sh
Script tested on GCP VM running RHEL8
> Add ML prerequisites script for podman on rhel8

- ML/ml_prereq_wsl.sh
Script tested on my local machine using WSL + Ubuntu installation.
> Add ML prerequisites script for WSL

- ML/ml_prereq_all.sh
Adapted the script to be able to install the prerequisites for WSL, Ubuntu and RHEL from the same script. Changes are:
- removed tests for EOL distros (RHEL7, ubuntu 16.* and 18.*, Amazon Linux)
- removed "sudo" from all places in the script - best practice (the script will run with sudo anyway)
- setting NEEDRESTART_MODE=a for Ubuntu needrestart, to suppres auto restart services prompt on apt upgrade - https://askubuntu.com/questions/1367139/apt-get-upgrade-auto-restart-services
- added a NVIDIA_DRIVER_BRANCH variable, to more easily update the script in the future
- removed all sections that are specific for RHEL7 and Amazon, as these distros are EOL
- added a check for Secure Boot, as I couldn't get the drivers to work with Secure Boot in a programmatic way
- rewrote the NVIDIA …
> Update ml_prereq script to contain all the required prerq installs, for RHEL, Ubunut and WSL in one single script

- ML/ml_prereq_all.sh
Added support for RHEL9.
Added switch to allow a check of the prereqs, without installing directly.
Changed from podman to docker for Ubuntu, as podman is not available in the official Ubuntu repos in the needed version.
> Added check switch to be able to perform a prereq check only.
